version: '3'
services:
  debian-container:
    build:
      dockerfile: debian/dockerfile
    ports:
      - 5000:5000   
    volumes:
      - ./IA_WebCreator:/srv/IA_WebCreator
    networks:
      - my-network

  angular:
    build:
      context: angular
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules
    networks:
      - my-network

networks:
  my-network:
