# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "maxhamon/debian12"

  config.vm.synced_folder "../IA_WebCreator", "/home/vagrant/IA_WebCreator"

  config.disksize.size = '30GB'

  config.vm.provider "virtualbox" do |vb|

    vb.memory = "2048"

  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update && apt-get install \
    -y --no-install-recommends python3 python3-virtualenv

    apt-get install tmux -y
    apt-get install htop -y

    VIRTUAL_ENV=/opt/venv
    python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV

    echo 'source /opt/venv/bin/activate' >> /home/vagrant/.bashrc

    source /opt/venv/bin/activate


    pip install openai


  SHELL
end
