# Utilisez l'image de base Debian
FROM debian:12

# Définissez un répertoire de travail
WORKDIR /srv/IA_WebCreator

# Mettez à jour les paquets et installaton des divers programmes
# RUN apt-get update && apt-get install -y python3
# RUN apt-get install pip -y
# RUN apt install -y python3.11-venv

# Installation du venv il y en a besoin pour l'installation de torch
# RUN /bin/bash -c "python3 -m venv /srv/IA_WebCreator/venv"
# RUN python3 -m venv /srv/IA_WebCreator/venv
# RUN python3 -m venv venv

RUN apt-get update && apt-get install \
  -y --no-install-recommends python3 python3-virtualenv

ENV VIRTUAL_ENV=/opt/venv

RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install torch
RUN pip install transformers
RUN pip install accelerate
RUN pip install bitsandbytes
RUN pip install scipy
RUN pip install safetensors

# Démarrez votre application, si nécessaire
CMD ["tail", "-f", "/dev/null"]
# CMD ["python3", "/srv/IA_WebCreator/bin/IA.py"]
